<a href="https://colab.research.google.com/github/SobiaNoorAI/Data-Seekho-Data-Science-Mastery-Program/blob/main/ecommerce_sales_pandas_eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files

In [2]:
uploaded = files.upload()

Saving Sales_Large.csv to Sales_Large.csv
Saving Products_Large.csv to Products_Large.csv
Saving Orders_Large.csv to Orders_Large.csv
Saving Customers_Large.csv to Customers_Large.csv

In [3]:
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

User uploaded file "Sales_Large.csv" with length 8020 bytes
User uploaded file "Products_Large.csv" with length 1325 bytes
User uploaded file "Orders_Large.csv" with length 14517 bytes
User uploaded file "Customers_Large.csv" with length 1612 bytes

In [4]:
uploaded

{'Sales_Large.csv': b'OrderID,Revenue,Discounts,Taxes\n1000,1755,30,65\n1001,1727,76,101\n1002,1834,25,23\n1003,896,94,123\n1004,1868,51,63\n1005,1178,80,106\n1006,1737,87,128\n1007,970,94,96\n1008,1895,86,168\n1009,946,35,36\n1010,857,38,86\n1011,1743,13,179\n1012,244,40,90\n1013,1203,63,114\n1014,871,68,35\n1015,1626,54,27\n1016,860,20,183\n1017,1010,8,54\n1018,594,33,186\n1019,683,56,47\n1020,1165,75,193\n1021,1017,33,163\n1022,1496,64,59\n1023,1527,8,171\n1024,1173,70,87\n1025,1710,64,118\n1026,997,31,62\n1027,922,63,172\n1028,901,88,96\n1029,200,79,98\n1030,331,56,161\n1031,386,84,123\n1032,1786,28,103\n1033,834,91,112\n1034,1933,97,185\n1035,1205,93,197\n1036,1382,20,30\n1037,212,3,85\n1038,1159,92,182\n1039,756,63,98\n1040,1576,25,117\n1041,1836,42,143\n1042,671,47,193\n1043,1018,79,32\n1044,858,64,67\n1045,1168,49,168\n1046,931,14,19\n1047,854,20,195\n1048,217,86,55\n1049,718,32,98\n1050,1830,14,85\n1051,1929,54,198\n1052,1288,29,30\n1053,240,45,82\n1054,232,76,71\n1055,1939,86,111\n1056,675,72,59\n1057,1182,51,25\n1058,940,19,73\n1059,1869,48,41\n1060,284,74,134\n1061,294,72,91\n1062,264,65,97\n1063,490,62,99\n1064,1517,74,59\n1065,1764,91,149\n1066,426,58,62\n1067,1331,31,182\n1068,1807,39,164\n1069,1592,72,123\n1070,752,8,156\n1071,339,22,56\n1072,732,79,64\n1073,1892,66,149\n1074,1947,28,160\n1075,1107,43,196\n1076,658,75,31\n1077,1987,100,38\n1078,248,21,54\n1079,1495,74,78\n1080,1467,28,140\n1081,1876,76,25\n1082,1552,71,192\n1083,1589,44,174\n1084,392,22,47\n1085,474,2,77\n1086,1917,64,20\n1087,1787,98,106\n1088,1358,78,35\n1089,1383,31,68\n1090,1012,1,59\n1091,1011,81,39\n1092,1022,63,168\n1093,625,28,10\n1094,520,54,148\n1095,385,57,58\n1096,316,71,32\n1097,1120,52,18\n1098,439,96,82\n1099,1942,20,195\n1100,837,47,170\n1101,908,61,94\n1102,333,31,96\n1103,1127,89,93\n1104,1170,34,162\n1105,1041,75,146\n1106,237,23,29\n1107,1713,66,30\n1108,1248,76,68\n1109,1638,78,92\n1110,994,5,154\n1111,1557,23,137\n1112,1301,89,151\n1113,1815,53,118\n1114,578,53,31\n1115,812,33,142\n1116,1096,12,60\n1117,957,7,130\n1118,417,31,30\n1119,1762,46,118\n1120,354,9,154\n1121,1866,59,13\n1122,891,59,158\n1123,1046,10,167\n1124,1935,92,197\n1125,698,64,96\n1126,537,62,179\n1127,787,80,171\n1128,1706,52,151\n1129,1202,37,76\n1130,1643,51,44\n1131,1583,67,180\n1132,714,17,173\n1133,955,42,140\n1134,1674,61,127\n1135,913,52,22\n1136,881,33,40\n1137,901,66,16\n1138,856,70,129\n1139,1606,89,105\n1140,1306,32,118\n1141,1070,80,121\n1142,1395,37,150\n1143,1944,0,171\n1144,1231,29,37\n1145,1933,20,187\n1146,617,44,44\n1147,1854,55,11\n1148,566,1,17\n1149,1634,52,177\n1150,1068,10,104\n1151,759,89,16\n1152,1558,4,164\n1153,1182,64,151\n1154,1242,48,102\n1155,1047,44,188\n1156,1883,25,81\n1157,266,24,16\n1158,702,50,176\n1159,870,38,78\n1160,1050,100,41\n1161,1763,56,173\n1162,1419,85,81\n1163,590,10,193\n1164,629,10,155\n1165,1479,26,159\n1166,868,24,196\n1167,1657,24,139\n1168,529,15,131\n1169,1888,51,62\n1170,1560,34,123\n1171,431,17,142\n1172,627,73,181\n1173,392,34,37\n1174,685,77,72\n1175,1939,63,187\n1176,988,84,48\n1177,1524,37,97\n1178,1497,27,96\n1179,1904,71,104\n1180,999,0,114\n1181,817,70,89\n1182,1493,88,84\n1183,944,26,119\n1184,1706,77,107\n1185,755,56,83\n1186,420,100,114\n1187,638,46,161\n1188,1419,35,19\n1189,1748,69,145\n1190,1857,18,167\n1191,784,10,150\n1192,1992,75,27\n1193,919,77,98\n1194,843,94,177\n1195,1264,9,59\n1196,1698,62,156\n1197,1709,67,33\n1198,1367,25,79\n1199,400,94,128\n1200,235,99,103\n1201,1670,70,128\n1202,1075,80,74\n1203,540,49,145\n1204,1249,70,116\n1205,1807,6,11\n1206,1463,100,165\n1207,2000,27,108\n1208,1513,94,116\n1209,676,83,36\n1210,639,49,94\n1211,825,24,68\n1212,1957,19,23\n1213,1656,27,107\n1214,1450,37,18\n1215,1666,61,11\n1216,1437,19,22\n1217,769,67,115\n1218,1575,95,146\n1219,546,9,84\n1220,1681,46,44\n1221,783,71,180\n1222,512,26,151\n1223,1135,49,71\n1224,904,6,84\n1225,1602,24,94\n1226,1773,3,15\n1227,884,10,193\n1228,969,90,45\n1229,1903,46,103\n1230,923,15,110\n1231,353,45,168\n1232,1895,67,55\n1233,1757,68,85\n1234,906,47,45\n1235,1498,24,60\n1236,805,73,47\n1237,794,5,160\n1238,873,61,75\n1239,1704,40,14\n1240,1599,28,124\n1241,1778,93,161\n1242,721,11,81\n1243,1429,28,187\n1244,1080,90,115\n1245,1668,87,38\n1246,353,49,95\n1247,1836,12,80\n1248,1866,10,86\n1249,1177,65,108\n1250,1894,92,133\n1251,531,40,60\n1252,1239,43,193\n1253,1739,82,31\n1254,1895,19,120\n1255,443,18,11\n1256,1709,46,195\n1257,723,87,27\n1258,1498,79,189\n1259,318,31,162\n1260,348,88,193\n1261,687,95,48\n1262,920,49,110\n1263,1162,37,101\n1264,229,82,91\n1265,1504,5,100\n1266,1089,9,60\n1267,411,31,22\n1268,1210,68,152\n1269,536,92,102\n1270,301,95,175\n1271,545,45,86\n1272,839,1,24\n1273,1001,59,114\n1274,501,77,100\n1275,675,54,91\n1276,849,88,25\n1277,1872,42,189\n1278,266,1,170\n1279,1163,28,199\n1280,450,47,138\n1281,620,45,177\n1282,1637,26,97\n1283,1863,84,92\n1284,1843,27,40\n1285,1257,96,185\n1286,507,3,48\n1287,1030,35,117\n1288,1133,13,94\n1289,1077,74,46\n1290,732,25,71\n1291,1626,97,76\n1292,1092,24,105\n1293,311,43,112\n1294,1980,32,63\n1295,1116,49,42\n1296,1825,73,80\n1297,1179,35,164\n1298,427,36,20\n1299,751,14,43\n1300,621,6,83\n1301,232,66,139\n1302,1589,21,56\n1303,1511,72,139\n1304,360,30,78\n1305,522,86,160\n1306,1173,43,122\n1307,1037,31,150\n1308,1408,93,43\n1309,511,78,83\n1310,1247,98,53\n1311,1762,95,154\n1312,1207,1,70\n1313,487,0,167\n1314,934,97,50\n1315,1542,27,41\n1316,1839,31,122\n1317,925,66,103\n1318,1029,19,143\n1319,643,74,42\n1320,1918,81,184\n1321,1332,15,125\n1322,1291,84,11\n1323,427,11,113\n1324,633,40,128\n1325,1561,90,65\n1326,1711,76,58\n1327,718,21,98\n1328,1813,96,62\n1329,1123,99,170\n1330,1255,61,114\n1331,1325,30,147\n1332,502,48,35\n1333,1361,17,80\n1334,1998,6,49\n1335,932,86,116\n1336,1214,70,88\n1337,1681,26,105\n1338,1624,1,73\n1339,1141,97,144\n1340,1643,49,87\n1341,1813,82,42\n1342,398,98,72\n1343,1452,34,114\n1344,717,95,88\n1345,1989,58,141\n1346,1322,65,83\n1347,1332,85,67\n1348,900,80,90\n1349,795,100,170\n1350,1875,87,51\n1351,1249,68,18\n1352,335,12,132\n1353,633,66,52\n1354,273,58,92\n1355,979,89,47\n1356,785,85,107\n1357,338,18,121\n1358,700,24,188\n1359,890,88,17\n1360,449,82,58\n1361,1160,71,71\n1362,1757,15,36\n1363,1741,37,161\n1364,787,7,34\n1365,1111,32,141\n1366,539,3,91\n1367,966,34,54\n1368,1889,68,138\n1369,1074,40,175\n1370,1677,98,173\n1371,419,39,71\n1372,1679,21,91\n1373,997,48,139\n1374,221,74,51\n1375,726,48,127\n1376,1693,48,195\n1377,1121,19,79\n1378,1132,35,129\n1379,1929,79,154\n1380,1809,67,81\n1381,1156,18,160\n1382,279,29,185\n1383,1593,45,54\n1384,1647,56,182\n1385,790,100,97\n1386,731,62,137\n1387,1754,98,53\n1388,1405,42,20\n1389,1744,75,117\n1390,1657,77,25\n1391,311,93,195\n1392,727,23,77\n1393,1684,42,132\n1394,1245,17,138\n1395,1542,81,154\n1396,281,15,14\n1397,1580,58,114\n1398,1317,63,140\n1399,1138,81,78\n1400,309,53,153\n1401,1593,37,13\n1402,1083,93,31\n1403,1975,19,44\n1404,1909,30,28\n1405,1317,51,140\n1406,363,5,24\n1407,1039,34,23\n1408,508,66,174\n1409,1191,53,75\n1410,1704,35,104\n1411,1052,73,97\n1412,1891,4,17\n1413,503,48,69\n1414,1292,5,80\n1415,1971,64,56\n1416,1147,54,117\n1417,432,8,45\n1418,1747,9,195\n1419,1176,46,18\n1420,466,5,173\n1421,1781,98,161\n1422,660,94,113\n1423,520,43,174\n1424,1603,2,159\n1425,1462,100,183\n1426,1667,20,53\n1427,1176,84,11\n1428,1058,99,69\n1429,1261,71,187\n1430,1320,90,10\n1431,1377,61,52\n1432,1305,38,185\n1433,1551,74,64\n1434,378,17,142\n1435,486,84,65\n1436,835,54,83\n1437,593,94,35\n1438,1946,41,40\n1439,1249,48,72\n1440,1678,81,140\n1441,417,43,160\n1442,204,21,99\n1443,349,90,80\n1444,227,68,149\n1445,645,77,197\n1446,847,81,198\n1447,1967,55,71\n1448,1995,64,71\n1449,1755,39,117\n1450,1040,51,105\n1451,655,42,197\n1452,361,22,185\n1453,1386,67,196\n1454,1194,38,70\n1455,328,21,59\n1456,1534,24,159\n1457,791,78,124\n1458,471,41,92\n1459,552,71,89\n1460,1111,10,185\n1461,234,20,106\n1462,415,100,123\n1463,289,78,191\n1464,1741,67,85\n1465,1083,21,164\n1466,441,71,56\n1467,1234,61,91\n1468,1693,11,53\n1469,1139,35,26\n1470,873,26,75\n1471,1038,31,27\n1472,929,72,15\n1473,1911,39,93\n1474,821,27,62\n1475,1747,2,24\n1476,472,35,47\n1477,1841,89,15\n1478,1873,20,26\n1479,1482,13,88\n1480,1263,57,133\n1481,1137,7,184\n1482,458,92,194\n1483,1694,86,194\n1484,517,17,10\n1485,843,74,40\n1486,1904,70,168\n1487,1851,60,38\n1488,1591,72,69\n1489,780,36,99\n1490,1325,80,22\n1491,284,9,72\n1492,1609,11,29\n1493,1374,1,115\n1494,611,5,39\n1495,1089,92,28\n1496,1338,49,95\n1497,770,8,172\n1498,1264,76,182\n1499,1882,5,141\n',
 'Products_Large.csv': b'ProductID,ProductName,Category,Price\n200,Report,Books,89\n201,Shake,Electronics,226\n202,Skill,Books,494\n203,Into,Home Appliances,160\n204,Responsibility,Books,479\n205,Card,Home Appliances,140\n206,Pull,Books,198\n207,Notice,Books,406\n208,Explain,Home Appliances,247\n209,Protect,Home Appliances,345\n210,Heavy,Accessories,124\n211,Process,Electronics,98\n212,Mind,Accessories,67\n213,Guy,Electronics,224\n214,Present,Home Appliances,287\n215,Both,Accessories,334\n216,Size,Home Appliances,293\n217,Despite,Books,367\n218,Answer,Accessories,487\n219,Truth,Accessories,448\n220,We,Electronics,472\n221,Hope,Electronics,292\n222,Price,Electronics,191\n223,Care,Electronics,335\n224,Friend,Electronics,428\n225,Nor,Books,466\n226,Suffer,Accessories,179\n227,North,Home Appliances,221\n228,Gun,Home Appliances,438\n229,Voice,Electronics,294\n230,Notice,Books,323\n231,Role,Home Appliances,82\n232,Dinner,Electronics,291\n233,Enter,Books,383\n234,Just,Books,390\n235,Level,Home Appliances,367\n236,Maybe,Accessories,350\n237,Behavior,Accessories,190\n238,Your,Books,219\n239,Performance,Home Appliances,256\n240,Dog,Accessories,377\n241,Argue,Electronics,133\n242,Like,Electronics,440\n243,Available,Accessories,258\n244,Guess,Accessories,166\n245,Catch,Accessories,89\n246,Dream,Home Appliances,229\n247,Happen,Electronics,57\n248,System,Books,360\n249,Story,Accessories,360\n',


# A) Clean Data

In [5]:
import pandas as pd

 **Open Products File**

In [6]:
products=pd.read_csv('Products_Large.csv')
print(products)

    ProductID     ProductName         Category  Price
0         200          Report            Books     89
1         201           Shake      Electronics    226
2         202           Skill            Books    494
3         203            Into  Home Appliances    160
4         204  Responsibility            Books    479
5         205            Card  Home Appliances    140
6         206            Pull            Books    198
7         207          Notice            Books    406
8         208         Explain  Home Appliances    247
9         209         Protect  Home Appliances    345
10        210           Heavy      Accessories    124
11        211         Process      Electronics     98
12        212            Mind      Accessories     67
13        213             Guy      Electronics    224
14        214         Present  Home Appliances    287
15        215            Both      Accessories    334
16        216            Size  Home Appliances    293
17        217         Despite            Books    367
18        218          Answer      Accessories    487
19        219           Truth      Accessories    448
20        220              We      Electronics    472
21        221            Hope      Electronics    292
22        222           Price      Electronics    191
23        223            Care      Electronics    335
24        224          Friend      Electronics    428
25        225             Nor            Books    466
26        226          Suffer      Accessories    179
27        227           North  Home Appliances    221
28        228             Gun  Home Appliances    438
29        229           Voice      Electronics    294
30        230          Notice            Books    323
31        231            Role  Home Appliances     82
32        232          Dinner      Electronics    291
33        233           Enter            Books    383
34        234            Just            Books    390
35        235           Level  Home Appliances    367
36        236           Maybe      Accessories    350
37        237        Behavior      Accessories    190
38        238            Your            Books    219
39        239     Performance  Home Appliances    256
40        240             Dog      Accessories    377
41        241           Argue      Electronics    133
42        242            Like      Electronics    440
43        243       Available      Accessories    258
44        244           Guess      Accessories    166
45        245           Catch      Accessories     89
46        246           Dream  Home Appliances    229
47        247          Happen      Electronics     57
48        248          System            Books    360
49        249           Story      Accessories    360

## 1.1 Check missing values in Products

In [7]:
products.isnull().sum()

ProductID      0
ProductName    0
Category       0
Price          0
dtype: int64

## 1.2 Check Duplicate values in Products

In [8]:
products.duplicated().sum()

0

**Open Customers File**

In [9]:
customers=pd.read_csv('Customers_Large.csv')
print(customers)

    CustomerID               Name   Region    Segment
0            1  Christina Harrell     East  Corporate
1            2      David Charles     East  Corporate
2            3      Cheryl Harris     East  Corporate
3            4       Cameron King  Central  Corporate
4            5          Tanya Kim     West  Corporate
5            6       Lauren Walls     West  Wholesale
6            7     Christine King     West  Wholesale
7            8      Derek Sanders  Central     Retail
8            9    Steven Sullivan  Central  Corporate
9           10        Shawn Bryan     West  Corporate
10          11    Michael Morales    North     Retail
11          12        Carol Brown     West  Corporate
12          13      Denise Martin  Central  Wholesale
13          14        Eric Snyder  Central  Wholesale
14          15     Sharon Leonard    South  Corporate
15          16     Rachel Hartman     West  Corporate
16          17         Mark Silva     West  Corporate
17          18        Justin Carr    South     Retail
18          19      Deborah Kelly     East  Wholesale
19          20  Vanessa Mcpherson    South  Wholesale
20          21   Kristine Daniels  Central     Retail
21          22          Lori Cole  Central  Wholesale
22          23         Randy Duke    North     Retail
23          24        Laura Nunez    South  Corporate
24          25        Denise Mack     West  Corporate
25          26     Robert Andrews    South     Retail
26          27    Michelle Gordon    North  Wholesale
27          28     Bradley Huerta  Central  Corporate
28          29      Crystal Green    North  Wholesale
29          30   Alexander Chavez  Central     Retail
30          31        Sherri Knox    South  Wholesale
31          32   Michael Hamilton     East  Wholesale
32          33      William Brown     East  Wholesale
33          34         Gina Scott    North  Corporate
34          35        Lori Prince     East  Corporate
35          36  Dr. Steven Walter     West     Retail
36          37     Lori Phelps MD     West  Corporate
37          38          Luis Byrd    North     Retail
38          39       Taylor Moore    North     Retail
39          40         David Wong     West  Wholesale
40          41          Misty Kim     West  Corporate
41          42        Zachary Ray  Central  Corporate
42          43  Patricia Matthews     East     Retail
43          44        Maria Black  Central  Wholesale
44          45    Joseph Kemp DDS    North  Corporate
45          46       Megan Melton     West  Wholesale
46          47    Kimberly Crosby     East     Retail
47          48      Darrell Brady     East     Retail
48          49         David Cobb     East     Retail
49          50        Joshua Vang    South  Corporate

## 2.1 Check Missing Values in Customers

In [10]:
customers.isnull().sum()

CustomerID    0
Name          0
Region        0
Segment       0
dtype: int64

## 2.2 Duplicate Values in Customers

In [11]:
customers.duplicated().sum()

0

**Open Sales File**

In [12]:
sales=pd.read_csv('Sales_Large.csv')
print(sales)

     OrderID  Revenue  Discounts  Taxes
0       1000     1755         30     65
1       1001     1727         76    101
2       1002     1834         25     23
3       1003      896         94    123
4       1004     1868         51     63
..       ...      ...        ...    ...
495     1495     1089         92     28
496     1496     1338         49     95
497     1497      770          8    172
498     1498     1264         76    182
499     1499     1882          5    141

[500 rows x 4 columns]

## 3.1 Check Missing Values in Sales

In [13]:
sales.isnull().sum()

OrderID      0
Revenue      0
Discounts    0
Taxes        0
dtype: int64

## 3.2 Check Duplicate Values in Sales

In [14]:
sales.duplicated().sum()

0

**Open Orders File**

In [15]:
orders=pd.read_csv('Orders_Large.csv')
print(orders)

     TransactionID   OrderDate  CustomerID  ProductID  Quantity  TotalAmount
0             1000  2023-02-11           6        212         4          426
1             1001  2024-06-09          22        226         8          184
2             1002  2022-12-11          31        231         5          880
3             1003  2022-12-18          23        227        10          928
4             1004  2024-04-11          42        215         7          517
..             ...         ...         ...        ...       ...          ...
495           1495  2023-04-16          30        208         8          903
496           1496  2023-03-25          10        230         5          192
497           1497  2024-06-28          11        218         7          288
498           1498  2024-04-06          38        213         6          905
499           1499  2023-05-03          44        204         2          596

[500 rows x 6 columns]

## 4.1 Check Missing Values in Orders

In [16]:
orders.isnull().sum()

TransactionID    0
OrderDate        0
CustomerID       0
ProductID        0
Quantity         0
TotalAmount      0
dtype: int64

## 4.2 Check Duplicate Values in Orders

In [17]:
orders.duplicated().sum()

0

# B) Exploratory Data Analysis (EDA)

## 1.0 Monthly Sales

To display Monthly sales, we need
- Month from orders DataFrame/Table
- Revenue from sales DataFrame/Table

To get data from two DataFrames, we merge both DataFrames

Display Columns of Both DataFrames

In [18]:
sales.columns

Index(['OrderID', 'Revenue', 'Discounts', 'Taxes'], dtype='object')

In [19]:
orders.columns

Index(['TransactionID', 'OrderDate', 'CustomerID', 'ProductID', 'Quantity',
       'TotalAmount'],
      dtype='object')

New Column, Month

We see that there is no Column of Month in orders DataFrame

So, we have to extract month from OrderDate and save into new Column Month

In [25]:
# Convert 'OrderDate' to datetime objects
orders['OrderDate'] = pd.to_datetime(orders['OrderDate'])

# Extract the month from the 'OrderDate' column
orders['Month'] = orders['OrderDate'].dt.month

# Print the updated dataframe to see the new 'Month' column
orders

,TransactionID,OrderDate,CustomerID,ProductID,Quantity,TotalAmount,Month
0,1000,2023-02-11,6,212,4,426,2
1,1001,2024-06-09,22,226,8,184,6
2,1002,2022-12-11,31,231,5,880,12
3,1003,2022-12-18,23,227,10,928,12
4,1004,2024-04-11,42,215,7,517,4
...,...,...,...,...,...,...,...
495,1495,2023-04-16,30,208,8,903,4
496,1496,2023-03-25,10,230,5,192,3
497,1497,2024-06-28,11,218,7,288,6
498,1498,2024-04-06,38,213,6,905,4
499,1499,2023-05-03,44,204,2,596,5

Merge Sales and Orders DataFrames

In [27]:
merge_sales_orders = pd.merge(sales, orders, left_on='OrderID', right_on='TransactionID')
merge_sales_orders

,OrderID,Revenue,Discounts,Taxes,TransactionID,OrderDate,CustomerID,ProductID,Quantity,TotalAmount,Month
0,1000,1755,30,65,1000,2023-02-11,6,212,4,426,2
1,1001,1727,76,101,1001,2024-06-09,22,226,8,184,6
2,1002,1834,25,23,1002,2022-12-11,31,231,5,880,12
3,1003,896,94,123,1003,2022-12-18,23,227,10,928,12
4,1004,1868,51,63,1004,2024-04-11,42,215,7,517,4
...,...,...,...,...,...,...,...,...,...,...,...
495,1495,1089,92,28,1495,2023-04-16,30,208,8,903,4
496,1496,1338,49,95,1496,2023-03-25,10,230,5,192,3
497,1497,770,8,172,1497,2024-06-28,11,218,7,288,6
498,1498,1264,76,182,1498,2024-04-06,38,213,6,905,4
499,1499,1882,5,141,1499,2023-05-03,44,204,2,596,5

Monthly Sales by groupby()

Now, we can apply groupby() on merge data `merge_sales_orders` to get sales according to month

In [33]:
monthly_sales=merge_sales_orders.groupby(orders['Month'])['Revenue'].sum()
print(monthly_sales)

Month
1     47011
2     32035
3     43038
4     45891
5     56438
6     41153
7     58094
8     50186
9     45754
10    50169
11    45717
12    48513
Name: Revenue, dtype: int64

## 2.0 Customers Behavior

Similarly, we can sort customers who are producing more revenue

- For that we analyze merge data `merge_sales_orders` according to `CustomerID`

- Here, we use `head()` function to display Top 5 Customers

In [34]:
top_customers = merge_sales_orders.groupby('CustomerID')['Revenue'].sum().sort_values(ascending=False)
print(top_customers.head(5))

CustomerID
3     22198
16    20717
27    18103
34    17155
10    17004
Name: Revenue, dtype: int64

## 3.0 Product Performance

Similarly, we can sort products that are producing more revenue

- For that we analyze merge data `merge_sales_orders` according to `ProductID`

- Here, we use `head()` function to display Top 5 Products

In [35]:
top_products = merge_sales_orders.groupby('ProductID')['Revenue'].sum().sort_values(ascending=False)
print(top_products.head(5))

ProductID
215    19651
250    19350
221    17570
207    17297
231    16135
Name: Revenue, dtype: int64

# C) Feature Engineering

## 1.0 Revenue Per Product

To display Revenue Per Product , we need
- Quantity from orders DataFrame/Table
- Price from products DataFrame/Table

To get data from two DataFrames, we merge both DataFrames

In [38]:
orders.columns

Index(['TransactionID', 'OrderDate', 'CustomerID', 'ProductID', 'Quantity',
       'TotalAmount', 'Month', 'revenue_per_product'],
      dtype='object')

In [39]:
products.columns

Index(['ProductID', 'ProductName', 'Category', 'Price'], dtype='object')

Merge Orders and Product DataFrames

In [40]:
merge_orders_products = pd.merge(orders, products, on='ProductID')
merge_orders_products

,TransactionID,OrderDate,CustomerID,ProductID,Quantity,TotalAmount,Month,revenue_per_product,ProductName,Category,Price
0,1000,2023-02-11,6,212,4,426,2,268.0,Mind,Accessories,67
1,1001,2024-06-09,22,226,8,184,6,1432.0,Suffer,Accessories,179
2,1002,2022-12-11,31,231,5,880,12,410.0,Role,Home Appliances,82
3,1003,2022-12-18,23,227,10,928,12,2210.0,North,Home Appliances,221
4,1004,2024-04-11,42,215,7,517,4,2338.0,Both,Accessories,334
...,...,...,...,...,...,...,...,...,...,...,...
479,1495,2023-04-16,30,208,8,903,4,NaN,Explain,Home Appliances,247
480,1496,2023-03-25,10,230,5,192,3,NaN,Notice,Books,323
481,1497,2024-06-28,11,218,7,288,6,NaN,Answer,Accessories,487
482,1498,2024-04-06,38,213,6,905,4,NaN,Guy,Electronics,224
483,1499,2023-05-03,44,204,2,596,5,NaN,Responsibility,Books,479

Revenue Per Product by Quantity * Price

In [41]:
orders['revenue_per_product'] = merge_orders_products['Quantity'] * merge_orders_products['Price']
print(orders.head(5))

   TransactionID  OrderDate  CustomerID  ProductID  Quantity  TotalAmount  \
0           1000 2023-02-11           6        212         4          426
1           1001 2024-06-09          22        226         8          184
2           1002 2022-12-11          31        231         5          880
3           1003 2022-12-18          23        227        10          928
4           1004 2024-04-11          42        215         7          517

   Month  revenue_per_product
0      2                268.0
1      6               1432.0
2     12                410.0
3     12               2210.0
4      4               2338.0